# ========================================================================
# GLOBAL PROJECT CONFIGURATION
# This file serves as the single source of truth for all microservices.
# ========================================================================

[project]
name = "unified-document-processing-system"
version = "1.0.0"
description = "A system for processing documents from PDF to text and speech, with AI augmentation."

[paths]
base_logs_dir = "/tmp/logs"

[database]
user_database_dsn = "${USER_DATABASE_DSN}"

[ui_service]
http_address = ":8080"
max_upload_megabytes = 64

[png_to_text_service.prompts]
commentary_base = """

## ROLE AND GOAL
You are a technical editor preparing a raw document script for an audiobook narrator. Your goal is to create a clean, seamless, narration-ready script by augmenting the provided text with descriptions of its visual elements. This is an **augmentation** task, not a summarization task. Think of yourself as an accessibility narrator describing a scene for the visually impaired; you are adding the missing visual context.

---
## CRITICAL RULES
1.  **PRESERVE PROSE:** You MUST preserve the original prose. Do not summarize or significantly rephrase the text. Your only job is to clean up OCR artifacts and add descriptions for non-textual content.
2.  **NO HEADERS OR MARKDOWN:** The final output MUST be a single, continuous block of text. Do not use markdown, titles, or section headers.
3.  **NO EXPLICIT REFERENCES:** When describing a visual, weave the description directly and naturally into the narrative. NEVER say "The image shows..." or "Figure 1 contains...".
4.  **NO NARRATOR FLUFF:** Do not add conversational filler like "Welcome to the chapter" or "In this section, we will...". Stick to the source material.

---
## 3-STEP PROCESS
1.  **Clean Artifacts:** First, remove all headers, footers, and page numbers found in the OCR text. Integrate section titles (e.g., "Introduction") smoothly as the start of a new paragraph.
2.  **Augment with Visuals:** At the exact point where a visual element (figure, table, code block, formula, etc.) appears in the original document, insert a concise, natural-language description of its content. This is your primary task.
3.  **Format for Narration:** Handle acronyms for the narrator. The first time an acronym appears, write the full term followed by the acronym in parentheses, like "Peripheral Component Interface (PCI)". For ALL subsequent uses, format it with periods to signal that it should be spelled out: "P. C. I.".
"""

summary_base = """

## ROLE AND GOAL
You craft concise previews or recaps that help a listener understand the purpose of the upcoming page. Capture the central ideas, the structure of the argument, and the outcome of any computations or examples.

---
## CRITICAL RULES
1. Keep the summary to two or three natural sentences focused on intent and outcomes.
2. Highlight the purpose of major visuals or data displays without restating fine-grained commentary details.
3. Use clear prose with no markdown, bullets, or section headers.
4. After the summary, present the original OCR text exactly once; do not paraphrase or omit content.

---
## STRUCTURE
Open with the most important conclusion or question answered on the page. Mention secondary points or transitions that prepare the listener for what follows. Close by signalling how the listener should expect the narration to proceed (e.g., "The next section dives into..." when appropriate).
"""

[png_to_text_service.augmentation]
use_prompt_builder = true
parameters = {}

[png_to_text_service.augmentation.defaults.commentary]
enabled = true
custom_additions = ""

[png_to_text_service.augmentation.defaults.summary]
enabled = false
placement = "bottom"
custom_additions = ""

[png_to_text_service.gemini]
api_key_variable = "GEMINI_API_KEY"

[png_to_text_service.tts_defaults]
voice = "tara"
seed = 10
ngl = 8
top_p = 0.95
repetition_penalty = 1.1
temperature = 0.70

# ========================================================================
# TTS-SERVICE SPECIFIC CONFIGURATION
# ========================================================================
[tts_service]
model_path = "${TTS_MODEL_PATH}"
snac_model_path = "${SNAC_MODEL_PATH}"
seed = 10
ngl = 8
voice = "tara"
temperature = 0.70
top_p = 0.95
repetition_penalty = 1.1
timeout_seconds = 300
allowed_voices = ["default", "tara", "leah", "jess", "leo", "dan", "mia", "zac", "zoe"]

# ========================================================================
# PCM-TO-WAV-SERVICE SPECIFIC CONFIGURATION
# ========================================================================
[pcm_to_wav_service]
[pcm_to_wav_service.sox]
encoding = "signed-integer"
bits = 16
rate = 24000
channels = 1
input_type = "raw"
output_type = "wav"

# ========================================================================
# WAV-AGGREGATOR-SERVICE SPECIFIC CONFIGURATION
# ========================================================================
[wav_aggregator_service]
worker_pool_size = 10

# ========================================================================
# USER-DATABASE-SERVICE SPECIFIC CONFIGURATION
# ========================================================================
[user_database_service]
listen_address = "0.0.0.0:8085"
jwt_issuer = "book-expert-user-db"
jwt_audience = "book-expert"
access_token_ttl_minutes = 15
refresh_token_ttl_hours = 720
argon2_memory_kib = 19456
argon2_iterations = 3
argon2_parallelism = 1

# ========================================================================
# CONFIGURATOR SERVICE SPECIFIC CONFIGURATION
# (No specific configuration needed for configurator itself, it's a library)
# ========================================================================

[nats]
url = "nats://127.0.0.1:4222"
# PDF to PNG Service
pdf_stream_name = "PDF_JOBS"
pdf_consumer_name = "pdf-workers"
pdf_created_subject = "pdf.created"
pdf_object_store_bucket = "PDF_FILES"
# PNG to Text Service
png_stream_name = "PNG_PROCESSING"
png_consumer_name = "png-text-workers"
png_created_subject = "png.created"
png_object_store_bucket = "PNG_FILES"
text_object_store_bucket = "TEXT_FILES"  # New bucket for processed text
dead_letter_subject = "dead.letter"
text_stream_name = "TTS_JOBS"
# Text to Speech Service
tts_consumer_name = "tts-workers"
text_processed_subject = "text.processed"
audio_chunk_created_subject = "audio.chunk.created"
audio_object_store_bucket = "AUDIO_FILES"
# PCM to WAV Service
audio_processing_stream_name = "AUDIO_PROCESSING"
audio_processing_consumer_name = "pcm-to-wav-workers"
wav_created_subject = "wav.created"
wav_object_store_bucket = "WAV_FILES"
# WAV Aggregator Service
final_audio_created_subject = "final.audio.created"
final_audio_object_store_bucket = "FINAL_AUDIO_FILES"
wav_consumer_name = "wav-aggregator-workers"
wav_aggregator_kv_bucket = "WAV_AGGREGATOR_STATE"
