# ========================================================================
# GLOBAL CONFIGURATION
# ========================================================================

[project]
name = "unified-document-processing-system"
version = "1.0.0"
description = "A system for processing documents from PDF to text and speech, with AI augmentation."

[paths]
base_logs_dir = "/tmp/logs"

[nats]
url = "nats://127.0.0.1:4222"

[database]
user_database_dsn = "postgres://book_expert_user:b00k_3xp3rt@localhost:5432/book_expert_db"

# ========================================================================
# BOOK EXPERT SERVICE (Main Orchestrator)
# ========================================================================

[book_expert_service]
log_directory = "/tmp/logs"
log_filename = "book-expert-service.log"
watchdog_interval_seconds = 60
required_units = [
    "nats-server.service",
    "user-database.service"
]

# ========================================================================
# COST ESTIMATOR SERVICE
# ========================================================================

[cost_estimator_service]
currency = "USD"
page_block_size = 100
base_rate_cents_per_block = 200
default_augmentation_cents_per_block = 50
custom_commentary_cents_per_block = 100
custom_summary_cents_per_block = 100
maximum_prompt_characters = 500

# ========================================================================
# UI SERVICE
# ========================================================================

[ui_service]
http_address = ":8080"
max_upload_megabytes = 64

# UI Service produces PDF uploads to start the pipeline
[[ui_service.nats.streams]]
name = "PDFS"
subjects = ["book-expert.pdfs.created"]
storage = "file"
retention = "limits"
max_msgs = 10000
max_age = 86400

[[ui_service.nats.producers]]
subject = "book-expert.pdfs.created"
stream = "PDFS"

[[ui_service.nats.object_stores]]
bucket_name = "PDF_FILES"

# ========================================================================
# PDF TO PNG SERVICE
# ========================================================================

[pdf_to_png_service]
dead_letter_subject = "book-expert.pdf-to-png.dlq"

[[pdf_to_png_service.nats.streams]]
name = "PDFS"
subjects = ["book-expert.pdfs.created"]
storage = "file"
retention = "limits"
max_msgs = 10000
max_age = 86400

[[pdf_to_png_service.nats.streams]]
name = "PNGS"
subjects = ["book-expert.pngs.created"]
storage = "file"
retention = "limits"
max_msgs = 50000
max_age = 86400

[[pdf_to_png_service.nats.streams]]
name = "PDF_TO_PNG_DLQ"
subjects = ["book-expert.pdf-to-png.dlq"]
storage = "file"
retention = "limits"

[[pdf_to_png_service.nats.consumers]]
stream_name = "PDFS"
durable_name = "pdf-to-png-durable"
filter_subject = "book-expert.pdfs.created"
ack_policy = "explicit"
max_deliver = 3
max_ack_pending = 20
ack_wait = 300000000000

[[pdf_to_png_service.nats.producers]]
subject = "book-expert.pngs.created"
stream = "PNGS"

[[pdf_to_png_service.nats.object_stores]]
bucket_name = "PDF_FILES"

[[pdf_to_png_service.nats.object_stores]]
bucket_name = "PNG_FILES"

# ========================================================================
# PNG TO TEXT SERVICE
# ========================================================================

[png_to_text_service]
dead_letter_subject = "book-expert.png-to-text.dlq"

[png_to_text_service.prompts]
commentary_base = """

## ROLE AND GOAL
You are a technical editor preparing a raw document script for an audiobook narrator. Your goal is to create a clean, seamless, narration-ready script by augmenting the provided text with descriptions of its visual elements. This is an **augmentation** task, not a summarization task. Think of yourself as an accessibility narrator describing a scene for the visually impaired; you are adding the missing visual context.

---
## CRITICAL RULES
1.  **PRESERVE PROSE:** You MUST preserve the original prose. Do not summarize or significantly rephrase the text. Your only job is to clean up OCR artifacts and add descriptions for non-textual content.
2.  **NO HEADERS OR MARKDOWN:** The final output MUST be a single, continuous block of text. Do not use markdown, titles, or section headers.
3.  **NO EXPLICIT REFERENCES:** When describing a visual, weave the description directly and naturally into the narrative. NEVER say "The image shows..." or "Figure 1 contains...".
4.  **NO NARRATOR FLUFF:** Do not add conversational filler like "Welcome to the chapter" or "In this section, we will...". Stick to the source material.

---
## 3-STEP PROCESS
1.  **Clean Artifacts:** First, remove all headers, footers, and page numbers found in the OCR text. Integrate section titles (e.g., "Introduction") smoothly as the start of a new paragraph.
2.  **Augment with Visuals:** At the exact point where a visual element (figure, table, code block, formula, etc.) appears in the original document, insert a concise, natural-language description of its content. This is your primary task.
3.  **Format for Narration:** Handle acronyms for the narrator. The first time an acronym appears, write the full term followed by the acronym in parentheses, like "Peripheral Component Interface (PCI)". For ALL subsequent uses, format it with periods to signal that it should be spelled out: "P. C. I.".
"""

summary_base = """

## ROLE AND GOAL
You craft concise previews or recaps that help a listener understand the purpose of the upcoming page. Capture the central ideas, the structure of the argument, and the outcome of any computations or examples.

---
## CRITICAL RULES
1. Keep the summary to two or three natural sentences focused on intent and outcomes.
2. Highlight the purpose of major visuals or data displays without restating fine-grained commentary details.
3. Use clear prose with no markdown, bullets, or section headers.
4. After the summary, present the original OCR text exactly once; do not paraphrase or omit content.

---
## STRUCTURE
Open with the most important conclusion or question answered on the page. Mention secondary points or transitions that prepare the listener for what follows. Close by signalling how the listener should expect the narration to proceed (e.g., "The next section dives into..." when appropriate).
"""

[png_to_text_service.augmentation]
use_prompt_builder = true
parameters = {}

[png_to_text_service.augmentation.defaults.commentary]
enabled = true
custom_additions = ""

[png_to_text_service.augmentation.defaults.summary]
enabled = false
placement = "bottom"
custom_additions = ""

[png_to_text_service.gemini]
api_key_variable = "${GEMINI_API_KEY}"

[png_to_text_service.tts_defaults]
voice = "tara"
seed = 10
ngl = 8
top_p = 0.95
repetition_penalty = 1.1
temperature = 0.70

[[png_to_text_service.nats.streams]]
name = "PNGS"
subjects = ["book-expert.pngs.created"]
storage = "file"
retention = "limits"
max_msgs = 50000
max_age = 86400

[[png_to_text_service.nats.streams]]
name = "TEXTS"
subjects = ["book-expert.texts.created"]
storage = "file"
retention = "limits"
max_msgs = 50000
max_age = 86400

[[png_to_text_service.nats.streams]]
name = "PNG_TO_TEXT_DLQ"
subjects = ["book-expert.png-to-text.dlq"]
storage = "file"
retention = "limits"

[[png_to_text_service.nats.consumers]]
stream_name = "PNGS"
durable_name = "png-to-text-durable"
filter_subject = "book-expert.pngs.created"
ack_policy = "explicit"
max_deliver = 3
max_ack_pending = 20
ack_wait = 600000000000

[[png_to_text_service.nats.producers]]
subject = "book-expert.texts.created"
stream = "TEXTS"

[[png_to_text_service.nats.object_stores]]
bucket_name = "PNG_FILES"

[[png_to_text_service.nats.object_stores]]
bucket_name = "TEXT_FILES"

# ========================================================================
# TTS SERVICE
# ========================================================================

[tts_service]
model_path = "${TTS_MODEL_PATH}"
snac_model_path = "${SNAC_MODEL_PATH}"
seed = 10
ngl = 8
voice = "tara"
temperature = 0.70
top_p = 0.95
repetition_penalty = 1.1
timeout_seconds = 300
allowed_voices = ["default", "tara", "leah", "jess", "leo", "dan", "mia", "zac", "zoe"]
dead_letter_subject = "book-expert.tts.dlq"

[[tts_service.nats.streams]]
name = "TEXTS"
subjects = ["book-expert.texts.created"]
storage = "file"
retention = "limits"
max_msgs = 50000
max_age = 86400

[[tts_service.nats.streams]]
name = "AUDIO_CHUNKS"
subjects = ["book-expert.audio.chunk.created"]
storage = "file"
retention = "limits"
max_msgs = 100000
max_age = 86400

[[tts_service.nats.streams]]
name = "TTS_DLQ"
subjects = ["book-expert.tts.dlq"]
storage = "file"
retention = "limits"

[[tts_service.nats.consumers]]
stream_name = "TEXTS"
durable_name = "tts-durable"
filter_subject = "book-expert.texts.created"
ack_policy = "explicit"
max_deliver = 3
max_ack_pending = 100
ack_wait = 300000000000

[[tts_service.nats.producers]]
subject = "book-expert.audio.chunk.created"
stream = "AUDIO_CHUNKS"

[[tts_service.nats.object_stores]]
bucket_name = "AUDIO_FILES"

# ========================================================================
# PCM TO WAV SERVICE
# ========================================================================

[pcm_to_wav_service]
dead_letter_subject = "book-expert.pcm-to-wav.dlq"

[pcm_to_wav_service.sox]
encoding = "signed-integer"
bits = 32
rate = 24000
channels = 1
input_type = "raw"
output_type = "wav"

[[pcm_to_wav_service.nats.streams]]
name = "AUDIO_CHUNKS"
subjects = ["book-expert.audio.chunk.created"]
storage = "file"
retention = "limits"
max_msgs = 100000
max_age = 86400

[[pcm_to_wav_service.nats.streams]]
name = "WAV_FILES"
subjects = ["book-expert.wav.created"]
storage = "file"
retention = "limits"
max_msgs = 100000
max_age = 86400

[[pcm_to_wav_service.nats.streams]]
name = "PCM_TO_WAV_DLQ"
subjects = ["book-expert.pcm-to-wav.dlq"]
storage = "file"
retention = "limits"

[[pcm_to_wav_service.nats.consumers]]
stream_name = "AUDIO_CHUNKS"
durable_name = "pcm-to-wav-durable"
filter_subject = "book-expert.audio.chunk.created"
ack_policy = "explicit"
max_deliver = 3
max_ack_pending = 50
ack_wait = 300000000000

[[pcm_to_wav_service.nats.producers]]
subject = "book-expert.wav.created"
stream = "WAV_FILES"

[[pcm_to_wav_service.nats.object_stores]]
bucket_name = "AUDIO_FILES"

[[pcm_to_wav_service.nats.object_stores]]
bucket_name = "WAV_FILES"

# ========================================================================
# WAV AGGREGATOR SERVICE
# ========================================================================

[wav_aggregator_service]
worker_pool_size = 10
dead_letter_subject = "book-expert.wav-aggregator.dlq"

[[wav_aggregator_service.nats.streams]]
name = "WAV_FILES"
subjects = ["book-expert.wav.created"]
storage = "file"
retention = "limits"
max_msgs = 100000
max_age = 86400

[[wav_aggregator_service.nats.streams]]
name = "FINAL_AUDIO"
subjects = ["book-expert.final.audio.created"]
storage = "file"
retention = "limits"
max_msgs = 10000
max_age = 86400

[[wav_aggregator_service.nats.streams]]
name = "WAV_AGGREGATOR_DLQ"
subjects = ["book-expert.wav-aggregator.dlq"]
storage = "file"
retention = "limits"

[[wav_aggregator_service.nats.consumers]]
stream_name = "WAV_FILES"
durable_name = "wav-aggregator-durable"
filter_subject = "book-expert.wav.created"
ack_policy = "explicit"
max_deliver = 3
max_ack_pending = 50
ack_wait = 600000000000

[[wav_aggregator_service.nats.producers]]
subject = "book-expert.final.audio.created"
stream = "FINAL_AUDIO"

[[wav_aggregator_service.nats.object_stores]]
bucket_name = "WAV_FILES"

[[wav_aggregator_service.nats.object_stores]]
bucket_name = "FINAL_AUDIO_FILES"

[wav_aggregator_service.nats.key_value]
bucket_name = "WAV_AGGREGATOR_STATE"

# ========================================================================
# USER DATABASE SERVICE
# ========================================================================

[user_database_service]
base_url = "http://localhost:8085"
listen_address = "0.0.0.0:8085"
jwt_issuer = "book-expert-user-db"
jwt_audience = "book-expert"
access_token_ttl_minutes = 15
refresh_token_ttl_hours = 720
argon2_memory_kib = 19456
argon2_iterations = 3
argon2_parallelism = 1

